version: "2"
services:
  server:
    container_name: server-container
    restart: always
    build: ./server
    command: sh -c 'npm run db'
    ports:
      - "3001:3001"
    links:
      - db
  db:
    container_name: db-container
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: usersreports
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
    ports:
      - "3307:3306"
    volumes:
      - serverDB:/data/db
  client:
      container_name: client-container
      restart: always
      build: ./client
      ports:
      - "3000:3000"
      links:
        - server

volumes:
  serverDB:
