name: CI Workflow

on:
  pull_request:
    branches: [master]

env:
  LINT_ERROR: "- :x: **Something went wrong with the linter, please review the modified files and check that they are formatted by our linter rules**"
  TEST_ERROR: "- :x: **Something went wrong with the tests, please review the unit test of your modified components and updated if necessary**"
  BUILD_ERROR: "- :x: **Something went wrong with the build, try running build on your local machine to see what is failing**"
  LINT_SUCCESS: "- :white_check_mark: **All files are well formatted**"
  TEST_SUCCESS: "- :white_check_mark: **All test passed**"
  BUILD_SUCCESS: "- :white_check_mark: **We could build without any problem**"
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  CI:
    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Install dependencies
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install -g @microsoft/rush

      - name: Run rush update if its a dependabot PR
        if: ${{ github.actor == 'dependabot[bot]' }}
        run: ./scripts/push-rush-update.sh

      - run: rush install
      - run: rush update
      - run: cd server && npx prisma generate
      - run: rush rebuild

      - name: lint
        id: lint
        if: always()
        run: rush lint

      - name: test
        id: test
        if: always()
        run: rush test

      - name: build
        id: build
        if: always()
        run: rush build

      - name: create lint success message
        id: lint_success
        if: always() && steps.lint.outcome == 'success'
        run: |
          echo "::set-output name=lint_message::$LINT_SUCCESS"
      - name: create lint error message
        id: lint_error
        if: always() && steps.lint.outcome != 'success'
        run: |
          echo "::set-output name=lint_message::$LINT_ERROR"

      - name: create test success message
        id: test_success
        if: always() && steps.test.outcome == 'success'
        run: |
          echo "::set-output name=test_message::$TEST_SUCCESS"
      - name: create test error message
        id: test_error
        if: always() && steps.test.outcome != 'success'
        run: |
          echo "::set-output name=test_message::$TEST_ERROR"

      - name: create build success message
        id: build_success
        if: always() && steps.build.outcome == 'success'
        run: |
          echo "::set-output name=build_message::$BUILD_SUCCESS"
      - name: create build error message
        id: build_error
        if: always() && steps.build.outcome != 'success'
        run: |
          echo "::set-output name=build_message::$BUILD_ERROR"

      - name: comment issue
        if: always()
        uses: actions/github-script@v6
        with:
          script: |
            const body = `
              ### CI Workflow Output
              ${{ steps.lint_success.outputs.lint_message }}${{ steps.lint_error.outputs.lint_message }}
              ${{ steps.test_success.outputs.test_message }}${{ steps.test_error.outputs.test_message }}
              ${{ steps.build_success.outputs.build_message }}${{ steps.build_error.outputs.build_message }}
              `
            github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: body
            })
